name: Deployment Custom Actions
on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: custom-action-project

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # code first must be fetched, so do not move this to custom actions
      - name: Load & cache dependencies
        id: cache-deps
        uses: ./.github/actions/caches-deps # also can reference directly from github repo eg. Karan02/custom-action-1
        with:
          caching: "false"
      - name: Output information
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/caches-deps # also can reference directly from github repo eg. Karan02/custom-action-1
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/caches-deps # also can reference directly from github repo eg. Karan02/custom-action-1
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: custom-action-project/dist
  deploy:
    permissions: #permissions for OIDC connect
      id-token: write
      contents: read
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist-files # this is important when working with subdirectories
      - name: Output contents
        run: ls
      # https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-aws
      # attached role S3FullAccess
      # with OIDC(open ID connection) we do not need aws access key and access id manually, commented out below
      # AWS -> IAM service -> Identity providers tab -> Add Provider
      - name: Get AWS permissions
        uses: aws-actions/configure-aws-credentials@v6 #action for AWS OIDC
        with:
          role-to-assume: arn:aws:iam::905418281563:role/github-actions-demo-1 # arn + s3 bucket (role)
          aws-region: ap-south-1
      - name: Deploy site
        id: deploy
        uses: ./.github/actions/deploy-s3-javascript
        # OR
        # uses: ./.github/actions/deploy-s3-docker # python environment code, need to be studied

        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # Must provide for docker action
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Must provide for docker action
        with:
          bucket: github-actions-test-001
          dist-folder: dist-files
          bucket-region: ap-south-1
        # run: echo "Deploying..."
      - name: Output Information
        run: |
          echo "Live URL: ${{ steps.deploy.outputs.website-url }}"

  # information:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v3 # get code first
  #     - name: Run custom action
  #       uses: ./.github/actions/deploy-s3-javascript # also can reference directly from github repo eg. Karan02/custom-action-1
