# Nodejs code for this is in Udemy lectures on github actions- docker section - starter project
# Service container - hosts testing database in contrast to real production database
name: Deployment (Container)

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "docker-project-separate/**"

env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo

defaults:
  run:
    working-directory: docker-project-separate

jobs:
  test:
    environment: testing
    runs-on: ubuntu-lates
    # container: # docker container, this job will run in container
    #   image: node:16
    #   # env:
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb # mongodb+srv
      MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017 # 'mongodb' - if using above commented container #service name here
      # or smmqkda.mongodb.net, this commented is atlas db
      MONGODB_USERNAME: root # or ${{ secrets.MONGODB_USERNAME }} #secrets in github settings `testing` environment
      MONGODB_PASSWORD: example # or ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    services: # defining service container
      mongodb: #name of service, can be anything
        image: mongo #services runs inside image
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root # intialize with this credentials
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
