name: Deployment Exercise 1 with env
on: [push, workflow_dispatch]
env: # env variable on workflow level
  MONGODB_DB_NAME: gha-demo
jobs:
  lint:
    # Job based environment variable
    # env:
    #   MONGODB_DB_NAME: xyz
    #   PORT: 4000
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # if you don't mention which repository to checkout, it will fetch this one
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..., DB ${{ env.MONGODB_DB_NAME }}"
