#Artifacts output files and folders - typically used for sharing log files, app binaries, etc.
#Job Outputs - Simple values - typically used for reuse a value in different jobs, ex name of a file generated in previous step

name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  test: #runner
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # if you don't mention which repository to checkout, it will fetch this one
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }} #hashFiles creates unique hash value based on combination of files contents
          # if above key changes, we will reinstall dependencies
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build: # runner
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }} #hashFiles creates unique hash value based on combination of files contents
          # if above key changes, then reinstall dependencies following:
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build #dist folder generated here is artifact
      - name: Publish JS filename
        id: publish # helps access data
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';' # linux-command: outputs the file name of js file
      - name: Upload artifacts
        uses: actions/upload-artifact@v4 # action, can be downloaded from different workflows and different jobs
        with:
          name: dist-files #identifier
          path: dist
          # path: |
          #   dist
          #   package.json
          # !path/**/*.tmp  - exclude
  deploy: # runner, this job runs on different machine
    needs: build # runs after 'build' job
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
