name: Reusable Deploy
on: workflow_call # allows to be called from other workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "Deploying and uploading ..."
